### ISSUE TITLE
Question: update without user invervention possible?

### ISSUE THREAD

**Issue by mirceaciu** [revanmj/Android-WVersionManager#6]
Looking for a system that would allow updating remove devices, inaccessible to any human intervention.
Will the update require a user to click an "install" button or not? Thank you

**Comment by revanmj** [comment]
For Android up to 11 no.

User installed apps cannot install APKs without user intervention (unless you root the system and use root access for that or have your app signed with system signature which is only possible with custom ROMs).

Only in Android 12 Google added possibility of silently updating, but that only works for when all below conditions are met:
- The installer (meaning app initiating install process) opts into the new behavior.
- The app that’s being installed targets API level 29 (Android 10) or higher.
- The installer is either updating itself or installing an update to an app it first installed.
- The installer declares the UPDATE_PACKAGES_WITHOUT_USER_ACTION permission.

From my understanding, once your app meets above requirements, silent update will work out of the box on Android 12 without any changes to the library itself.

**Comment by mirceaciu** [comment]
Fair enough, thank your for the informative question.

**Comment by revanmj** [comment]
I've read a little more on the subject and there is one way that's accessible for Android lower than 12, but it requires MDM service (Mobile Devices Management) like Microsoft Intune. Then you can remotely install apps via this service without the need for root. 

But I don't know if there are any free or local hosted services like that.
